
steps:
  - name: 'ubuntu'
    entrypoint: bash
    args:
    - -c
    - |
      source .env
      echo $$GCLOUD_PROJECT_NAME > _PROJECT_NAME
      echo $$GCLOUD_PROJECT_ID > _PROJECT_ID
      echo $$GCLOUD_PROJECT_REPO_NAME > _REPO_NAME
      echo $$GCLOUD_PROJECT_REGION > _REGION
      echo $$GCLOUD_PROJECT_REGION-docker.pkg.dev/$$GCLOUD_PROJECT_ID/$$GCLOUD_PROJECT_REPO_NAME/$$GCLOUD_PROJECT_NAME-image:$$GCLOUD_PROJECT_NAME > _TAG
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: bash
    args: 
      - -c
      - |
        source .env
        docker build --build-arg EMAIL_SMTP=$$EMAIL_SMTP \
             --build-arg EMAIL_PORT=$$EMAIL_PORT \
             --build-arg EMAIL_ADDRESS=$$EMAIL_ADDRESS \
             --build-arg EMAIL_PASSWORD="$$EMAIL_PASSWORD" \
             -t $(cat _TAG | tr -d '\r') ./backend
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: bash
    args: 
      - -c
      - docker push $(cat _TAG | tr -d '\r')
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args: 
      - -c 
      - gcloud run deploy $(cat _PROJECT_NAME | tr -d '\r') --region=$(cat _REGION | tr -d '\r') --image $(cat _TAG | tr -d '\r') --allow-unauthenticated

